### ISSUE TITLE
how to get _u cookie

### ISSUE THREAD

**Issue by dary123** [maximerenou/php-bing-ai#1]
how to get _u cookie

**Comment by maximerenou** [comment]
Hello,

Thanks for your feedback, I added a "How to get this cookie?" section to [README.md](https://github.com/maximerenou/php-bing-ai#usage)

Here it is:
1. Navigate to bing.com
2. Sign in using your Microsoft account
3. Back on bing.com, right-click and select "Inspect" - the browser console appears
4. Go to "Application" tab
5. Select "Cookies" > "https://www.bing.com/" in the sidebar
6. Search for "_U" cookie
7. Copy its content

Enjoy!

**Comment by dary123** [comment]
thanks
