### ISSUE TITLE
replies repeating

### ISSUE THREAD

**Issue by fabthecop** [maximerenou/php-bing-ai#10]
If I ask a plain `how are you?`

I get an usual
`fine thanks and you?`
`[16 remaining messages]`
(P.S.) how to remove the last line?

If I ask something like `recap me the latest 2 news today` I get 238 recursive repetitions!

**Comment by maximerenou** [comment]
Hello,

Could you please attach some code to help reproducing your error?

**Comment by fabthecop** [comment]
`list me 5 latest news today` after a plain `compose install` > cd examples folder > `php chat.php` produces this output including the last line that's undesirable:

> Here are some of the latest news today:
> Here are some of the latest news today:
> Here are some of the latest news today:
> Here are some of the latest news today:
> Here are some of the latest news today:
> Here are some of the latest news today:
> Here are some of the latest news today:
> Here are some of the latest news today:licans
> Here are some of the latest news today:licans are
> Here are some of the latest news today:licans are putting
> Here are some of the latest news today:licans are putting the
> Here are some of the latest news today:licans are putting the final
> Here are some of the latest news today:licans are putting the final touches
> Here are some of the latest news today:licans are putting the final touches on
> Here are some of the latest news today:licans are putting the final touches on a
> Here are some of the latest news today:licans are putting the final touches on a deal
> Here are some of the latest news today:licans are putting the final touches on a deal that
> Here are some of the latest news today:licans are putting the final touches on a deal that will
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S.
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt ceiling
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt ceiling for
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt ceiling for two
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years [
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years [^1^
> Here are some of the latest news today:licans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 202
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential campaign
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential campaign is
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential campaign is finally
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential campaign is finally here
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential campaign is finally here
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential campaign is finally here [
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential campaign is finally here [^2^
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Here are some of the latest news today:ated 2024 presidential campaign is finally here .
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Haw
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkey
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State [
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State [^3^
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Here are some of the latest news today:Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> Here are some of the latest news today:
> The White House and congressional Republicans are putting the final touches on a deal that will raise the U.S. debt ceiling for two years .
> Florida Gov. Ron DeSantis' much-anticipated 2024 presidential campaign is finally here .
> Florida Gov. Ron DeSantis will head to Iowa on Monday to kick off his presidential campaign and start a three-state tour that will begin with several stops in the Hawkeye State .
> 
> 
> Would you like me to look up more news?
> [19 remaining messages]

**Comment by maximerenou** [comment]
OK it looks like backspaces aren't working in your terminal so it produces multiple lines instead of updating the current line with the latest words sent by Bing.

You may want to adapt the example script for your local environment, or simply bypass this issue by commenting the following lines: 33, 36, 41 and 54 (add "//" at start of each line)
