### ISSUE TITLE
conversationSignature / UnauthorizedRequest errors

### ISSUE THREAD

**Issue by tomekkox** [maximerenou/php-bing-ai#15]
Hello I have some issues with trying to run this cool project :), please give me some advice to run it properly .

I already did this:
- clone this repo
- install composer require maximerenou/bing-ai
- change $cookie value

When i am trying run file examples\chat.php
```
PHP Warning:  Undefined array key "conversationSignature" in C:\xampp\htdocs\BING_GPT\php-bing-ai\src\Chat\Conversation.php on line 43

Warning: Undefined array key "conversationSignature" in C:\xampp\htdocs\BING_GPT\php-bing-ai\src\Chat\Conversation.php on line 43
Type "q" to quit
```
Then I am  trying to ask a question.
```
PHP Warning:  Undefined array key "conversationSignature" in C:\xampp\htdocs\BING_GPT\php-bing-ai\src\Chat\Conversation.php on line 43

Warning: Undefined array key "conversationSignature" in C:\xampp\htdocs\BING_GPT\php-bing-ai\src\Chat\Conversation.php on line 43
Type "q" to quit

> What is the biggest animal?
[DEBUG] Creating loop
[DEBUG] Connection open
[DEBUG] Sending first packet
[DEBUG] Packet received
[DEBUG] {}
[DEBUG] Sending start ping
[DEBUG] Packet received
[DEBUG] {"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"defaultChatName":null,"conversationId":"51D|BingProdUnAuthenticatedUsers|BF5DC74900B644F5FD598CB486DEF0443241E3538915A49241194","requestId":"3ecr3241b609-e96d-3vfdsa-bb30-cd6fd3aa0daa","telemetry":{"startTime":"2023-10-28T22:28:14.24534234Z"},"result":{"value":"UnauthorizedRequest","message":"The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=","error":"UnauthorizedRequest","renewCert":true,"serviceVersion":"20231027.276"}}}
- [DEBUG] Packet received
[DEBUG] {"type":3,"invocationId":"0"}
- [DEBUG] Connection closed
-
[1 remaining messages]

>
```
I tried to check the cookie value.
```
require __DIR__ . '/../vendor/autoload.php';
use \MaximeRenou\BingAI\BingAI;
$cookie = "MY COOKIE VALUE 1241241209120591059105";
$ai = new BingAI($cookie);
$valid = $ai->checkCookie();
echo $valid;
```
the value is "1"
```
php cookie_test.php
1
```

Other question Is this values from file Conversation.php has to be changed, if I want to use this by other language and region ?
```
 // User preferences
    public $tone = Tone::Balanced;
    public $locale = 'en-US';
    public $market = 'en-US';
    public $region = 'US';
    public $geolocation = null;
    
```

**Comment by beshoo** [comment]
+1

**Comment by martingerlero** [comment]
Hi, I have the same problem. Did anyone find the solution? Thank you

**Comment by jaketoolson** [comment]
Same here.

**Comment by martingerlero** [comment]
I think I found the solution. For them I modified the constructor of the Conversation.php file and the error disappeared. Try if that solves it. The constructor looked like this:

    public function __construct($cookie, $identifiers = null, $invocations = 0)
    {
        $this->cookie = $cookie;

        if (! is_array($identifiers))
            $identifiers = $this->createIdentifiers();
        $identifiers['conversationSignature'] = uniqid();
        //echo "Identifiers:";
        //print_r($identifiers);
        $this->id = $identifiers['conversationId'];
        $this->client_id = $identifiers['clientId'];
        $this->signature = $identifiers['conversationSignature'];
        $this->invocations = $invocations - 1;
    }

**Comment by simply-zaki** [comment]
> ```
> public function __construct($cookie, $identifiers = null, $invocations = 0)
> {
>     $this->cookie = $cookie;
> 
>     if (! is_array($identifiers))
>         $identifiers = $this->createIdentifiers();
>     $identifiers['conversationSignature'] = uniqid();
>     //echo "Identifiers:";
>     //print_r($identifiers);
>     $this->id = $identifiers['conversationId'];
>     $this->client_id = $identifiers['clientId'];
>     $this->signature = $identifiers['conversationSignature'];
>     $this->invocations = $invocations - 1;
> }
> ```
i tried this and it gets rid of the error, however now it just sends empty text 
here is my code for refrence : 
```<?php
require __DIR__ . '/vendor/autoload.php';
use MaximeRenou\BingAI\BingAI;
use MaximeRenou\BingAI\Chat\Prompt;

$cookie = "cookie";
$ai = new BingAI($cookie);

$conversation = $ai->createChatConversation();

// $text - Text-only version of Bing's answer
// $cards - Message objects array
list($text, $cards) = $conversation->ask(new Prompt("Hello World"));
echo "bing:".$text;
$ai = new BingAI($cookie);
$valid = $ai->checkCookie();
echo "<br>" . "is valid:" . $valid;
?>```

**Comment by maximerenou** [comment]
Hello,

Bing team added some breaking changes and security layers on its API since this package has been published.

I'm open to PR if someone's ready to go back digging!

Greetings

**Comment by typoworx-de** [comment]
Just had a look at it after noticing this great package obviously doesn't work anymore. Bing introduced that the chat-session isn't done using HTTP-Requests anymore and replaced it by wss (websocket). The websocket is initialized with a sec-token, but I didn't figure out where it is given or calculated.

I'll try some other packages or nodejs libs that may be able to provide a dockerized "wrapper" using a http-api that then will forward the gpt-requests using the an external service (having a look into https://www.npmjs.com/package/nodejs-gpt now).

**Comment by maximerenou** [comment]
Hello, this package actually uses websockets for the chat part. However, I do not plan on maintaining it, but feel free to fork it.
