### ISSUE TITLE
PHP 7.2.33 ,Package maximerenou/bing-ai has a PHP requirement incompatible with your PHP version, PHP extens     ions and Composer version   

### ISSUE THREAD

**Issue by dary123** [maximerenou/php-bing-ai#2]
PHP 7.2.33 ,Package maximerenou/bing-ai has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

**Comment by maximerenou** [comment]
Hello,

It seems that you're using an outdated PHP version. I published a new release that is compatible with PHP 7, so you can use it.

On a side note - please check that you're using a stable or LTS version of Composer 2 (`composer self-update --2`) and that you installed PHP cURL extension.

Enjoy
