### ISSUE TITLE
Chatbot usage

### ISSUE THREAD

**Issue by CatAnonymous** [maximerenou/php-bing-ai#3]
How to let the chatbot know the previous chat content?

**Comment by maximerenou** [comment]
Hello,

It remembers what you said before, until you shift to a new conversation. You can try examples/chat.php for a one shot conversation, or check the "resume conversation" feature in README.

Enjoy

**Comment by CatAnonymous** [comment]
> Xin chào,
> 
> It remembers what you said before, until you move on to a new conversation. You can try examples/chat.php for a one-time chat, or check the "continue conversation" feature in README.> 
> Enjoy

On the homepage of bing chat it is possible to create images by chatting. I hope you can write a sample code to be able to chat and create images at the same time

**Comment by CatAnonymous** [comment]
> Hello,
> 
> It remembers what you said before, until you shift to a new conversation. You can try examples/chat.php for a one shot conversation, or check the "resume conversation" feature in README.
> 
> Enjoy

 Did I use it correctly? Unexpected result.

```
session_start();

$ai = new BingAI($cookie);

if (isset($_SESSION['identifiers'])) {
    $data = json_decode($_SESSION['identifiers'], true);
    $conversation = $ai->createChatConversation($data);
} else {
    $conversation = $ai->createChatConversation();
    $data = $conversation->getIdentifiers();
    $_SESSION['identifiers'] = json_encode($data);
}

list($text, $messages) = $conversation->ask(new Prompt($message));

var_dump($data, $text);
```

**Comment by maximerenou** [comment]
> On the homepage of bing chat it is possible to create images by chatting. I hope you can write a sample code to be able to chat and create images at the same time

As far as I know it is not possible to use Bing Chat to generate images, yet - we have to use Image Creator. However, rest assure that I would implement it, if it gets out there !

**Comment by maximerenou** [comment]
> if (isset($_SESSION['identifiers'])) {
>     $data = json_decode($_SESSION['identifiers'], true);
>     $conversation = $ai->createChatConversation($data);
> }

In this condition, you must use `resumeChatConversation($data)` instead of `createChatConversation($data)`, or it will generate a new conversation anyway.

**Comment by CatAnonymous** [comment]
> > if (isset($_SESSION['identifiers'])) {
> > $data = json_decode($_SESSION['identifiers'], true);
> > $conversation = $ai->createChatConversation($data);
> > }
> 
> In this condition, you must use `resumeChatConversation($data)` instead of `createChatConversation($data)`, or it will generate a new conversation anyway.

Thankyou, its working
 There are 3 levels in bing ai, is this option available here?

**Comment by maximerenou** [comment]
Hello again,

Thanks for pointing that out! I added tone support today so you can choose it when starting a conversation:

```php
use MaximeRenou\BingAI\Chat\Tone;

$conversation = $ai->createChatConversation()
    ->withTone(Tone::Creative);

// Choices:
// Tone::Balanced (default)
// Tone::Creative
// Tone::Precise
```

Enjoy!

**Comment by CatAnonymous** [comment]
> Hello again,
> 
> Thanks for pointing that out! I added tone support today so you can choose it when starting a conversation:
> 
> ```
> use MaximeRenou\BingAI\Chat\Tone;
> 
> $conversation = $ai->createChatConversation()
>     ->withTone(Tone::Creative);
> 
> // Choices:
> // Tone::Balanced (default)
> // Tone::Creative
> // Tone::Precise
> ```
> 
> Enjoy!

Code does not work well on HTTP environment, CLI environment is good

**Comment by CatAnonymous** [comment]
I will try with websocket instead of SSE+ajax

**Comment by maximerenou** [comment]
This module isn't impacted by protocols, so you may have errors in your code. Keep in mind that Bing AI can be slow, so it's important to configure large timeouts.
Feel free to open a new issue if you find a bug related to it :)

**Comment by maximerenou** [comment]
Update: image generation is indeed available in creative mode, I added support for this and created a demo script: ˋexamples/multi.php`

Enjoy

**Comment by CatAnonymous** [comment]
> Cập nhật: tạo hình ảnh thực sự có sẵn trong sáng tạo, tôi đã thêm hỗ trợ cho việc này và tạo một bản demo tập lệnh: ˋexamples/multi.php` > > Tận hưởng Thậ 

> Update: image generation is indeed available in creative mode, I added support for this and created a demo script: ˋexamples/multi.php`
> 
> Enjoy

 very interesting, thanks
