### ISSUE TITLE
Fatal error: Uncaught Exception: Failed to init conversation

### ISSUE THREAD

**Issue by veks** [maximerenou/php-bing-ai#4]
Hi, how to fix the error? maximerenou/bing-ai/src/Chat/Conversation.php on line 87

Fatal error: Uncaught Exception: Failed to init conversation

**Comment by maximerenou** [comment]
Hello,

Could you please give a code sample? I cannot reproduce this error, and `examples/chat.php` is still working fine.
You may want to check that your `$cookie` is valid, using `checkCookie()` method.

Hope it helps

**Comment by veks** [comment]
Thanks for the answer, it turns out you need an account with another country.

**Comment by maximerenou** [comment]
Thanks for the feedback!
